run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_stage2"
json_out_config = "_stage2.json"


[parameters]

use_checkpoint = false

prior_file = "/home/kmll395/usr/src/MolecularAI/reinvent_core/priors/libinvent_transformer_pubchem.prior"
agent_file = "/home/kmll395/usr/src/MolecularAI/reinvent_core/priors/libinvent_transformer_pubchem.prior"
smiles_file = "scaffold.smi"

summary_csv_prefix = "stage2"

batch_size = 100
randomize_smiles = false


[learning_strategy]

type = "dap"
sigma = 128
rate = 0.0001


[diversity_filter]

type = "PenalizeSameSmiles"
penalty_multiplier = 0.5


[inception]

memory_size = 50
sample_size = 10


[[stage]]
termination = "simple"
max_score = 1.0
max_steps = 200

chkpt_file = 'stage2.chkpt'

[stage.scoring]
type = "geometric_mean"
filename = "stage2_scoring.toml"
